name: nearby_connections
description: Plugin for the android NearbyConnections API. Bytes and Files Supported.
version: 3.3.0
homepage: https://github.com/mannprerak2/nearby_connections

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pkmnapps.nearby_connections
        pluginClass: NearbyConnectionsPlugin
      ios:
        pluginClass: NearbyConnectionsPlugin
